### ISSUE TITLE
The size of the terminal window increases when you click on the settings icon.

### ISSUE THREAD

**Issue by DmitrySkibitsky** [martyr-deepin/deepin-terminal-gtk#169] opened 2019-06-02 12:59 UTC
The size of the terminal window increases when you click on the settings icon.
This error also occurs when calling the context menu in the terminal

![deepin-screen-recorder_Select area_20190602155444](https://user-images.githubusercontent.com/20288556/58761636-2cada980-854f-11e9-9313-d6c86ffa84b6.gif)

```log
yaourt deepin-terminal 
1 community/deepin-terminal 3.2.5-1 (deepin-extra) [installed]
```

**Comment by chirs241097** [comment] 2019-06-03 02:39
Possible duplicate of #168.

**Comment by BLumia** [comment] 2019-06-07 12:07
Should be resolved in 3.2.5.1, please update the package :)

**Closed as completed** 2019-06-07 12:06 UTC
